DROP DATABASE IF EXISTS tickets;
CREATE DATABASE tickets;
USE tickets;

CREATE TABLE `localidades` (
    id INT(11) UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
    tipo VARCHAR(40) NOT NULL,
    descripcion VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

CREATE TABLE `usuarios` (
    id INT(11) UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
    nombre VARCHAR(40) NOT NULL,
    usuario VARCHAR(40) NOT NULL UNIQUE,
    clave VARCHAR(40) NOT NULL,
    correo VARCHAR(40) NOT NULL UNIQUE,
    isAdmin TINYINT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

CREATE TABLE `asientos` (
    id INT(11) UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
    categoria VARCHAR(40) NOT NULL,
    descripcion VARCHAR(40) NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

CREATE TABLE `eventos` (
    id INT(11) UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
    localidad_id INT(11) UNSIGNED NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    fechaCreacion TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FOREIGN KEY (localidad_id) REFERENCES localidades(id),
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

CREATE TABLE `localidades_asientos` (
    id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
    localidad_id INT(11) UNSIGNED NOT NULL,
    asientos_id INT(11) UNSIGNED NOT NULL,
    CONSTRAINT FOREIGN KEY (localidad_id) REFERENCES localidades(id),
    CONSTRAINT FOREIGN KEY (asientos_id) REFERENCES asientos(id),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

CREATE TABLE `boletosComprados` (
    id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
	usuarios_id INT(11) UNSIGNED NOT NULL,
    eventos_id  INT(11) UNSIGNED NOT NULL,
    asientos_id INT(11) UNSIGNED NOT NULL UNIQUE, -- unque, dos usuarios no pueden comprar el mismo boleto
    fechaCreacion TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FOREIGN KEY (usuarios_id) REFERENCES usuarios(id),
    CONSTRAINT FOREIGN KEY (asientos_id) REFERENCES asientos(id),
    CONSTRAINT FOREIGN KEY (eventos_id) REFERENCES eventos(id),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;